spring:
  datasource:
    url: jdbc:postgresql://ep-delicate-silence-a9nepk6u.gwc.azure.neon.tech/appdb?sslmode=require
    username: appdb_owner
    password: E19GHblZDxKi
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 22951390455-585u7p4qgrhdpmvuau8mkle4l90g3u20.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true  # Impostalo su 'true' per assicurarti che venga verificata la presenza dei template
