spring:
  datasource:
    url: jdbc:postgresql://ep-delicate-silence-a9nepk6u.gwc.azure.neon.tech:5432/appdb?sslmode=require
    username: appdb_owner
    password: E19GHblZDxKi
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
