name: Sync Fork with Latest Changes
on:
  push:
    branches:
      - develop
      - main
      - feature/authentication/frontend
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Sync with fork
        run: |
          git config user.name "dbuser03"
          git config user.email "d.buser@campus.unimib.it"
          git remote add fork https://github.com/dbuser03/${{ github.event.repository.name }}.git
          git fetch --all
          for branch in $(git branch -r | grep -v '\->' | grep -v 'origin/HEAD' | sed 's/origin\///'); do
            git checkout $branch
            git merge origin/$branch
            git push fork $branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
